### ISSUE TITLE
[Stage + KeyCloak] - API Key Generation

### ISSUE THREAD

**Issue by MitchellShiell** [overture-stack/composer#2]
### Summary

We want to generate API keys from Stage using Keycloak

### Description

From the Stage profile UI, when running Keycloak and Stage together, we cannot generate an API key. It seems to fail silently, which causes Keycloak to become non-responsive. 

### Expected Behavior
Stage makes a get request, and keycloak responds with an API key

### Actual Behavior

Stage generates the request. However, it just loops without any browser log/error. Here is the log from the stage container
 
```
protected proxy - proxing to target:https://keycloak:8443/realms/myrealm/apikey/api_key path:?sort=isRevoked&sortOrder=ASC&user_id=aed9b1ee-a126-4026-b7ce-e12cc59691e1&limit=1000
protected proxy - proxing to target:https://keycloak:8443/realms/myrealm/protocol/openid-connect/token path:
```

Interestingly while this is happening, you get the same spinning wheel treatment from keycloak when trying to access anything, such as the admin console on 8443/admin. This is the console log from the browser when trying to access 8443/admin

<img width="1545" alt="Screenshot 2024-05-28 at 1 46 17 PM" src="https://github.com/overture-stack/composer/assets/59712867/e002d2c2-34ee-4369-84da-c71788631467">

Nothing in logs within the keycloak container 

When directly supplying the API request in postman keycloak responds appropriately.

running wget from shell in container:

```
/usr/src $ wget --post-data="client_id=webclient&client_secret=ikksyrYaKX07acf4hpGrpKWcUGaFkEdM&grant_type=client_credentials" \
    --header="Content-Type: application/x-www-form-urlencoded" \
    https://key>      --header="Content-Type: application/x-www-form-urlencoded" \
    https://keycloak:8443/realms/myrealm/protocol/openid-connect/token

# Response:
Connecting to keycloak:8443 (192.168.224.6:8443)
08EBFFFFFF7F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889:
ssl_client: SSL_connect
wget: error getting response: Connection reset by peer
/usr/src $ 

```
### Steps to Reproduce

1. Clone repo: 
```
git clone -b develop https://github.com/overture-stack/composer.git
```
2. run compose
```
docker compose up -d
```
3. Go to localhost:8443/admin login with `admin`, `admin123`
4. Create a new user with the following info

| Field/Setting                  | Value                       |
|------------------------|-----------------------------|
| Username               | admin                       |
| Email                  | admin@example.com           |
| Email Verified         | Yes                         |
| First Name             | admin                       |
| Last Name              | example                     |
| From the Credentials Tab | Create a new password       |
| From the Groups Tab      | Join the admin group        |

 5. go to localhost:3000 and login in with the credentials `admin`, `admin123`
 6. Try to generate an API key from the profile UI. 

### Potential Solution

Providing stage with a self signed SSL cert

### Environment

Relevant code within the repo 

```
  # ==========================
  # Stage
  # ==========================
  stage:
    image: ghcr.io/overture-stack/stage:297e6eb
    container_name: stage
    platform: linux/amd64
    depends_on:
      arranger-server:
        condition: service_started
      keycloak:
        condition: service_started
    ports:
      - "3000:3000"
    environment:
      # Arranger Integration
      NEXT_PUBLIC_ARRANGER_DOCUMENT_TYPE: analysis
      NEXT_PUBLIC_ARRANGER_INDEX: analysis_centric
      NEXT_PUBLIC_ARRANGER_API_URL: arranger-server:5050
      NEXT_PUBLIC_ARRANGER_MANIFEST_COLUMNS: repositories.code, analysis.analysis_id, object_id, file.index_file.file_type, file.index_file.name, file.index_file.size, file.index_file.md5sum, file.index_file.object_id, donors.donor_id, donors.specimens.samples.sample_id, study_id
      # Score Integration
      NEXT_PUBLIC_SCORE_API_URL: score:8087
      # Keycloak Integration
      NEXT_PUBLIC_AUTH_PROVIDER: keycloak
      ACCESSTOKEN_ENCRYPTION_SECRET: super_secret
      SESSION_ENCRYPTION_SECRET: this_is_a_super_secret_secret
      NEXT_PUBLIC_KEYCLOAK_HOST: https://keycloak:8443 
      NEXT_PUBLIC_KEYCLOAK_REALM: myrealm
      NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: webclient
      KEYCLOAK_CLIENT_SECRET: ikksyrYaKX07acf4hpGrpKWcUGaFkEdM
      NEXT_PUBLIC_KEYCLOAK_PERMISSION_AUDIENCE: song
      # Stage Configs
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      NEXTAUTH_URL: http://localhost:3000/api/auth
      NEXT_PUBLIC_LAB_NAME: Overture Composer Portal
      NEXT_PUBLIC_DEBUG: true
      NEXT_PUBLIC_SHOW_MOBILE_WARNING: true
    networks:
      - db-network
      - index-network
 ```
     
```
  # ==========================
  # Keycloak 
  # ==========================
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak
    depends_on:
      keycloak-db:
        condition: service_healthy
    ports:
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_HOSTNAME: localhost
      KC_HEALTH_ENABLED: true 
    volumes:
      - ./configurationFiles/keycloakConfigs/server.keystore:/opt/keycloak/conf/server.keystore
      - ./configurationFiles/keycloakConfigs/keycloak-apikeys-1.0.1.jar:/opt/keycloak/providers/keycloak-apikeys.jar
      - ./configurationFiles/keycloakConfigs/myrealm-realm.json:/opt/keycloak/data/import/myrealm-realm.json
      - ./configurationFiles/keycloakConfigs/myrealm-users-0.json:/opt/keycloak/data/import/myrealm-users-0.json
    networks:
      - db-network
    command: >
      start
      --import-realm
      --db=postgres
      --db-url=jdbc:postgresql://keycloak-db:5432/keycloakDb
      --db-username=admin
      --db-password=admin123
      --https-key-store-file=/opt/keycloak/conf/server.keystore
      --https-key-store-password=password
```
