### ISSUE TITLE
[Maestro] - "Couldn't resolve server kafka:9092"

### ISSUE THREAD

**Issue by MitchellShiell** [overture-stack/composer#3]
## Description

Maestro produces the following logs when running:
```
2024-05-27 | 22:51:05.612 | 1 | scheduling-1 | WARN | org.apache.kafka.clients.ClientUtils | Couldn't resolve server kafka:9092 from bootstrap.servers as DNS resolution failed for kafka
2024-05-27 | 22:51:05.612 | 1 | scheduling-1 | ERROR | org.springframework.cloud.stream.binding.BindingService | Failed to create consumer binding; retrying in 30 seconds
```

## Possible Fix
- networking/reference to Kafka within the environment variables 

Here is maestros relevant env variables
```
      # Kafka Configurations
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka:9092
      SPRING_CLOUD_STREAM_BINDINGS_SONGINPUT_DESTINATION: song_analysis
```

Here is the Kafka part of the compose:
```

  # ==========================
  # Kafka
  # ==========================
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --list --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
```

Lastly this is a link to a couple of files for reference:
- [demo portal infra values.yml](https://github.com/oicr-softeng/overture-infra/blob/demo/envs/prod/stateless/maestro/values.yml)
- [Maestro Application.yml](https://github.com/overture-stack/maestro/blob/master/maestro-app/src/main/resources/config/application.yml)

## Steps to Reproduce

1. Clone repo: 
```
git clone -b develop https://github.com/overture-stack/composer.git
```
2. run compose

```
docker compose up -d
```

## Environment
* Version used: Maestro: 07a3a41 Kafka: Latest
